### ISSUE TITLE
Desktop - mobile_side_bar: FileSystemException - path = '/Users/..../_settings.json'

### ISSUE THREAD

**Issue by MichelDiz** [AppleEducate/plugins#73]
What means this error? the path doesn't exist. The example or anywhere says that I have to have a file "mobile_side_bar_settings.json".

```
** BUILD SUCCEEDED **                                                   
                                                                        
Building macOS application...     
(...)
[ERROR:flutter/lib/ui/ui_dart_state.cc(144)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Users/micheldiz/Library/Containers/com.app/Data/.config/mobile_side_bar_settings.json' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)               
#1      _File.openSync (dart:io/file_impl.dart:487:5)                   
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)          
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)          
#4      LocalStorage._init (package:localstorage/localstorage.dart:78:15)
<asynchronous suspension>                                               
#5      new LocalStorage._internal.<anonymous closure> (package:localstorage/localstorage.dart:45:18)
<asynchronous suspension>                                               
#6      new Future.<anonymous closure> (dart:async/future.dart:174:37)  
#7      _rootRun (dart:async/zone.dart:1120:38)                         
#8      _CustomZone.run (dart:async/zone.dart:1021:19)                  
#9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)             
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#11     _rootRun (dart:async/zone.dart:1124:13)                         
#12     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)   
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by rodydavis** [comment]
It may throw the error at first before it creates the file. I need to do better error handling on it though
